name: singlanguage12
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Cupertino icons
  cupertino_icons: ^1.0.8

  # Required packages (updated compatible versions)
#  camera: ^0.11.2
  google_fonts: ^6.3.1
  video_player: ^2.6.1
  path_provider: ^2.0.15
  speech_to_text: ^7.0.0
  http: ^1.0.0
  audioplayers: ^6.5.0
  fluttertoast: ^8.2.1
  http_parser: ^4.0.2
  image: ^4.1.0
  flutter_sound: ^9.28.0            # ⚠️ Updated for Flutter 3.x compatibility
#  permission_handler: ^12.0.1
  camera: ^0.10.5+5
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0             # ⚠️ Latest lints

flutter:
  uses-material-design: true
